name: CI/CD

on:
  push:
    branches: [ devin/initial-setup/19394 ]
  pull_request:
    branches: [ devin/initial-setup/19394 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: echo 'Placeholder for running tests'
